app1/urls.py
from django.urls import path
from app1.views import *

app_name='app1'

urlpatterns=[
    path('rks/',rks,name='rks'),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='app2'

urlpatterns=[
    path('singh/',singh,name='singh'),
]

project11/urls.py
from django.contrib import admin
from django.urls import path,include
import app1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),

]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app3/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def rks(request):
    return render(request,'rks.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def singh(request):
    return render(request,'singh.html')

app3/views.py
from django.shortcuts import render

# Create your views here.

templates/rks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hello good morning </h1>
        <h2>how are uuuu</h2>
        <a href="{% url 'app2:singh' %}"><h1>click here go to app1</h1></a>
        
    </center>
</body>
</html>

templates/singh.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>i am fine</h1>
        <h2>what about you </h2>
        <a href="{% url 'app1:rks' %}"><h1>go back to rks file</h1></a>

    </center>
    
</body>
</html>